source 'https://rubygems.org'
<%- gems %>

<% if (typeof theme_path != 'undefined' && theme_path) { %>
# Load gem dependencies from the theme
theme_gemfile = File.join(File.dirname(__FILE__), "<%- theme_path %>/Gemfile")
if File.exists?(theme_gemfile)
  puts "Loading #{theme_gemfile} ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(theme_gemfile)
end
<% } %>
