steps:
  - label: ':hammer: Build'
    command:
      - npm ci
      - npm pack
    plugins:
      - docker#v3.3.0:
          image: 'node:10'
          volumes:
            - './:/app'

  - label: ':jest: Test'
    command:
      - npm ci
      - npm test
    plugins:
      - docker#v3.3.0:
          image: 'node:10'
          volumes:
            - './:/app'
